In [137]:
import numpy as np
import pandas as pd
import os
from  yaml import safe_load
import tqdm
import pickle

In [21]:
filenames = []
for file in os.listdir('t20s'):
    filenames.append(os.path.join('t20s', file))

In [22]:
filenames[0:5]

['t20s\\1001349.yaml',
 't20s\\1001351.yaml',
 't20s\\1001353.yaml',
 't20s\\1004729.yaml',
 't20s\\1007655.yaml']

In [23]:
final_df = pd.DataFrame()
counter = 1
for file in tqdm.tqdm(filenames):
    with open(file, 'r') as f:
        df = pd.json_normalize(safe_load(f))
        df['match_id'] = counter
        final_df = pd.concat([final_df, df], ignore_index=True)
        counter += 1
        
final_df

100%|██████████| 5341/5341 [1:07:46<00:00,  1.31it/s]

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-18,2,6,[2017-02-17],male,T20,5.0,Sri Lanka,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-19,2,6,[2017-02-19],male,T20,2.0,Sri Lanka,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-23,1,6,[2017-02-22],male,T20,NaN,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.91,2016-09-12,1,6,[2016-09-05],male,T20,NaN,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2016-06-19,1,6,[2016-06-18],male,T20,NaN,Zimbabwe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5336,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-03-05,2,6,[2016-03-04],male,T20,6.0,Pakistan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5337,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.91,2016-03-08,1,6,[2016-03-06],male,T20,8.0,India,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5338,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.91,2016-02-03,1,6,[2016-02-03],male,T20,NaN,Netherlands,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
5339,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2016-09-12,1,6,[2016-09-06],male,T20,NaN,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5340,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-09-12,1,6,[2016-09-09],male,T20,4.0,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
final_df

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-18,2,6,[2017-02-17],male,T20,5.0,Sri Lanka,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-19,2,6,[2017-02-19],male,T20,2.0,Sri Lanka,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-23,1,6,[2017-02-22],male,T20,NaN,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.91,2016-09-12,1,6,[2016-09-05],male,T20,NaN,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2016-06-19,1,6,[2016-06-18],male,T20,NaN,Zimbabwe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5336,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-03-05,2,6,[2016-03-04],male,T20,6.0,Pakistan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5337,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.91,2016-03-08,1,6,[2016-03-06],male,T20,8.0,India,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5338,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.91,2016-02-03,1,6,[2016-02-03],male,T20,NaN,Netherlands,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
5339,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2016-09-12,1,6,[2016-09-06],male,T20,NaN,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5340,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-09-12,1,6,[2016-09-09],male,T20,4.0,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
final_df.shape

(5341, 8174)

In [29]:
final_df['info.gender'].value_counts()

info.gender
male      3366
female    1975
Name: count, dtype: int64

In [33]:
final_df['info.gender'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [35]:
final_df = final_df[final_df['info.gender'] == 'male']

In [37]:
final_df.drop('info.gender', axis = 1, inplace = True)

In [40]:
final_df.columns

Index(['innings', 'meta.data_version', 'meta.created', 'meta.revision',
       'info.balls_per_over', 'info.dates', 'info.match_type',
       'info.outcome.by.wickets', 'info.outcome.winner', 'info.overs',
       ...
       'info.registry.people.Muhammad Kaleem',
       'info.registry.people.Usman Mushtaq',
       'info.registry.people.Mohammad Shahid',
       'info.registry.people.Muktar Ali',
       'info.registry.people.Mohammad Usman',
       'info.registry.people.VS Wategaonkar',
       'info.registry.people.Farhan Ahmed',
       'info.registry.people.Khurram Manzoor', 'info.registry.people.P Negi',
       'info.registry.people.Hafiz Qaleem'],
      dtype='str', length=8173)

In [42]:
final_df['info.overs'].value_counts()

info.overs
20    3358
50       8
Name: count, dtype: int64

In [44]:
final_df = final_df[final_df['info.overs'] == 20]

In [94]:
final_df.drop(columns = [col for col in final_df.columns if "info.registry" in col], inplace = True)

In [95]:
final_df

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.dates,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.players.Costa Rica,info.players.Ivory Coast,info.players.Suriname,info.players.Turks and Caicos Island,info.players.Timor-Leste,info.players.Zambia,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-18,2,6,[2017-02-17],T20,5.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-19,2,6,[2017-02-19],T20,2.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-23,1,6,[2017-02-22],T20,NaN,Australia,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.91,2016-09-12,1,6,[2016-09-05],T20,NaN,Hong Kong,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2016-06-19,1,6,[2016-06-18],T20,NaN,Zimbabwe,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5336,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-03-05,2,6,[2016-03-04],T20,6.0,Pakistan,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5337,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.91,2016-03-08,1,6,[2016-03-06],T20,8.0,India,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5338,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.91,2016-02-03,1,6,[2016-02-03],T20,NaN,Netherlands,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5339,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2016-09-12,1,6,[2016-09-06],T20,NaN,Australia,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5340,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-09-12,1,6,[2016-09-09],T20,4.0,Australia,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
for i in final_df.columns:
    print(i)

innings
meta.data_version
meta.created
meta.revision
info.balls_per_over
info.dates
info.match_type
info.outcome.by.wickets
info.outcome.winner
info.overs
info.player_of_match
info.players.Australia
info.players.Sri Lanka
info.teams
info.toss.decision
info.toss.winner
info.umpires
info.venue
match_id
info.city
info.outcome.by.runs
info.players.Hong Kong
info.players.Ireland
info.players.India
info.players.Zimbabwe
info.players.Bangladesh
info.players.New Zealand
info.players.South Africa
info.players.England
info.match_type_number
info.players.West Indies
info.neutral_venue
info.outcome.result
info.outcome.method
info.players.Pakistan
info.players.Scotland
info.players.Netherlands
info.players.Oman
info.players.United Arab Emirates
info.players.Papua New Guinea
info.players.ICC World XI
info.players.Nepal
info.outcome.eliminator
info.players.Thailand
info.players.Uganda
info.players.Malaysia
info.players.Botswana
info.players.Lesotho
info.players.Malawi
info.players.Namibia
info.players.Sierra Leone
info.players.Mozambique
info.players.China
info.players.Kuwait
info.players.Philippines
info.players.Vanuatu
info.players.United States of America
info.players.Germany
info.players.Italy
info.players.Nigeria
info.players.Tanzania
info.players.Rwanda
info.players.Kenya
info.players.Japan
info.players.Indonesia
info.players.Fiji
info.players.Samoa
info.players.Canada
info.players.Ghana
info.players.Guernsey
info.players.Denmark
info.players.Norway
info.players.Jersey
info.players.Maldives
info.players.Mali
info.players.Singapore
info.players.Qatar
info.players.South Korea
info.players.Bermuda
info.players.Cayman Islands
info.players.Portugal
info.players.Spain
info.players.Gibraltar
info.players.Bhutan
info.players.Saudi Arabia
info.players.Bahrain
info.players.Iran
info.players.Austria
info.players.Belgium
info.players.Luxembourg
info.players.Czech Republic
info.players.Isle of Man
info.players.Bulgaria
info.players.Romania
info.players.Greece
info.players.Serbia
info.players.Malta
info.players.France
info.players.Sweden
info.players.Finland
info.players.Eswatini
info.players.Cameroon
info.players.Hungary
info.players.Estonia
info.players.Cyprus
info.players.Switzerland
info.players.Argentina
info.players.Brazil
info.players.Seychelles
info.players.Swaziland
info.players.Belize
info.players.Bahamas
info.players.Panama
info.players.Barbados
info.players.Israel
info.players.Turkey
info.players.Croatia
info.players.Slovenia
info.toss.uncontested
info.players.Cook Islands
info.players.St Helena
info.players.Gambia
info.players.Cambodia
info.players.Myanmar
info.players.Mongolia
info.players.Chile
info.players.Mexico
info.players.Costa Rica
info.players.Ivory Coast
info.players.Suriname
info.players.Turks and Caicos Island
info.players.Timor-Leste
info.players.Zambia
info.supersubs.New Zealand
info.supersubs.South Africa
info.bowl_out
info.outcome.bowl_out

In [97]:
final_df.drop(columns = [col for col in final_df.columns if "info.players" in col], inplace= True)

In [98]:
back_up = final_df.copy

In [99]:
final_df.columns

Index(['innings', 'meta.data_version', 'meta.created', 'meta.revision',
       'info.balls_per_over', 'info.dates', 'info.match_type',
       'info.outcome.by.wickets', 'info.outcome.winner', 'info.overs',
       'info.player_of_match', 'info.teams', 'info.toss.decision',
       'info.toss.winner', 'info.umpires', 'info.venue', 'match_id',
       'info.city', 'info.outcome.by.runs', 'info.match_type_number',
       'info.neutral_venue', 'info.outcome.result', 'info.outcome.method',
       'info.outcome.eliminator', 'info.toss.uncontested',
       'info.supersubs.New Zealand', 'info.supersubs.South Africa',
       'info.bowl_out', 'info.outcome.bowl_out'],
      dtype='str')

In [109]:
final_df = final_df[['innings', 'info.dates', 'info.teams', 'info.outcome.winner', 'info.venue', 'match_id', 'info.city', 'info.bowl_out']]

In [110]:
final_df

,innings,info.dates,info.teams,info.outcome.winner,info.venue,match_id,info.city,info.bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],"[Australia, Sri Lanka]",Sri Lanka,Melbourne Cricket Ground,1,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],"[Australia, Sri Lanka]",Sri Lanka,"Simonds Stadium, South Geelong",2,Victoria,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],"[Australia, Sri Lanka]",Australia,Adelaide Oval,3,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],"[Ireland, Hong Kong]",Hong Kong,"Bready Cricket Club, Magheramason",4,Londonderry,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],"[Zimbabwe, India]",Zimbabwe,Harare Sports Club,5,NaN,NaN
...,...,...,...,...,...,...,...,...
5336,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-03-04],"[Pakistan, Sri Lanka]",Pakistan,Shere Bangla National Stadium,5337,Mirpur,NaN
5337,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",[2016-03-06],"[Bangladesh, India]",India,Shere Bangla National Stadium,5338,Mirpur,NaN
5338,"[{'1st innings': {'team': 'Netherlands', 'deli...",[2016-02-03],"[United Arab Emirates, Netherlands]",Netherlands,ICC Academy,5339,Dubai,NaN
5339,"[{'1st innings': {'team': 'Australia', 'delive...",[2016-09-06],"[Sri Lanka, Australia]",Australia,Pallekele International Cricket Stadium,5340,NaN,NaN
5340,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-09-09],"[Sri Lanka, Australia]",Australia,R Premadasa Stadium,5341,Colombo,NaN

In [114]:
final_df.iloc[0]['innings'][0]['1st innings']

{'team': 'Australia',
 'deliveries': [{0.1: {'batsman': 'AJ Finch',
    'bowler': 'SL Malinga',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {0.2: {'batsman': 'AJ Finch',
    'bowler': 'SL Malinga',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {0.3: {'batsman': 'AJ Finch',
    'bowler': 'SL Malinga',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {0.4: {'batsman': 'M Klinger',
    'bowler': 'SL Malinga',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {0.5: {'batsman': 'M Klinger',
    'bowler': 'SL Malinga',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {0.6: {'batsman': 'M Klinger',
    'bowler': 'SL Malinga',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
  {1.1: {'batsman': 'M Klinger',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {1.2: {'batsman': 'M Klinger',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {1.3: {'batsman': 'AJ Finch',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {1.4: {'batsman': 'AJ Finch',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {1.5: {'batsman': 'AJ Finch',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
  {1.6: {'batsman': 'AJ Finch',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {2.1: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {2.2: {'batsman': 'AJ Finch',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {2.3: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {2.4: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {2.5: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
  {2.6: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {3.1: {'batsman': 'AJ Finch',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {3.2: {'batsman': 'AJ Finch',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {3.3: {'batsman': 'M Klinger',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {3.4: {'batsman': 'AJ Finch',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {3.5: {'batsman': 'M Klinger',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
  {3.6: {'batsman': 'M Klinger',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {4.1: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
  {4.2: {'batsman': 'AJ Finch',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
  {4.3: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
  {4.4: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
  {4.5: {'batsman': 'M Klinger',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {4.6: {'batsman': 'AJ Finch',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {5.1: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {5.2: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'extras': {'wides': 1},
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
  {5.3: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {5.4: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {5.5: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {5.6: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {5.7: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {6.1: {'batsman': 'AJ Finch',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {6.2: {'batsman': 'M Klinger',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {6.3: {'batsman': 'AJ Finch',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {6.4: {'batsman': 'AJ Finch',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {6.5: {'batsman': 'M Klinger',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {6.6: {'batsman': 'AJ Finch',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {7.1: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {7.2: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {7.3: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {7.4: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'extras': {'byes': 1},
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
  {7.5: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
  {7.6: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {8.1: {'batsman': 'AJ Finch',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {8.2: {'batsman': 'M Klinger',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
  {8.3: {'batsman': 'AJ Finch',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {8.4: {'batsman': 'M Klinger',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {8.5: {'batsman': 'M Klinger',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {8.6: {'batsman': 'M Klinger',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {9.1: {'batsman': 'M Klinger',
    'bowler': 'S Prasanna',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {9.2: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {9.3: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {9.4: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {9.5: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
  {9.6: {'batsman': 'AJ Finch',
    'bowler': 'S Prasanna',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {10.1: {'batsman': 'AJ Finch',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {10.2: {'batsman': 'AJ Finch',
    'bowler': 'PADLR Sandakan',
    'extras': {'legbyes': 1},
    'non_striker': 'M Klinger',
    'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
  {10.3: {'batsman': 'M Klinger',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0},
    'wicket': {'fielders': ['SL Malinga'],
     'kind': 'caught',
     'player_out': 'M Klinger'}}},
  {10.4: {'batsman': 'TM Head',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {10.5: {'batsman': 'TM Head',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {10.6: {'batsman': 'TM Head',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'AJ Finch',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {11.1: {'batsman': 'AJ Finch',
    'bowler': 'DAS Gunaratne',
    'non_striker': 'TM Head',
    'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
  {11.2: {'batsman': 'AJ Finch',
    'bowler': 'DAS Gunaratne',
    'non_striker': 'TM Head',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {11.3: {'batsman': 'AJ Finch',
    'bowler': 'DAS Gunaratne',
    'non_striker': 'TM Head',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0},
    'wicket': {'fielders': ['SL Malinga'],
     'kind': 'caught',
     'player_out': 'AJ Finch'}}},
  {11.4: {'batsman': 'TM Head',
    'bowler': 'DAS Gunaratne',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {11.5: {'batsman': 'MC Henriques',
    'bowler': 'DAS Gunaratne',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {11.6: {'batsman': 'TM Head',
    'bowler': 'DAS Gunaratne',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {12.1: {'batsman': 'TM Head',
    'bowler': 'S Prasanna',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {12.2: {'batsman': 'TM Head',
    'bowler': 'S Prasanna',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {12.3: {'batsman': 'MC Henriques',
    'bowler': 'S Prasanna',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {12.4: {'batsman': 'TM Head',
    'bowler': 'S Prasanna',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {12.5: {'batsman': 'TM Head',
    'bowler': 'S Prasanna',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {12.6: {'batsman': 'MC Henriques',
    'bowler': 'S Prasanna',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {13.1: {'batsman': 'MC Henriques',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {13.2: {'batsman': 'MC Henriques',
    'bowler': 'SL Malinga',
    'extras': {'wides': 1},
    'non_striker': 'TM Head',
    'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
  {13.3: {'batsman': 'MC Henriques',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {13.4: {'batsman': 'TM Head',
    'bowler': 'SL Malinga',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {13.5: {'batsman': 'TM Head',
    'bowler': 'SL Malinga',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {13.6: {'batsman': 'MC Henriques',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {13.7: {'batsman': 'TM Head',
    'bowler': 'SL Malinga',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {14.1: {'batsman': 'TM Head',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {14.2: {'batsman': 'MC Henriques',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'TM Head',
    'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
  {14.3: {'batsman': 'TM Head',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {14.4: {'batsman': 'MC Henriques',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'TM Head',
    'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
  {14.5: {'batsman': 'MC Henriques',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'TM Head',
    'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
  {14.6: {'batsman': 'TM Head',
    'bowler': 'PADLR Sandakan',
    'non_striker': 'MC Henriques',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {15.1: {'batsman': 'MC Henriques',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'TM Head',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0},
    'wicket': {'fielders': ['CK Kapugedera'],
     'kind': 'caught',
     'player_out': 'MC Henriques'}}},
  {15.2: {'batsman': 'TM Head',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {15.3: {'batsman': 'AJ Turner',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'TM Head',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {15.4: {'batsman': 'AJ Turner',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {15.5: {'batsman': 'TM Head',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {15.6: {'batsman': 'TM Head',
    'bowler': 'JRMVB Sanjaya',
    'extras': {'wides': 1},
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
  {15.7: {'batsman': 'TM Head',
    'bowler': 'JRMVB Sanjaya',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
  {16.1: {'batsman': 'AJ Turner',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {16.2: {'batsman': 'AJ Turner',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
  {16.3: {'batsman': 'AJ Turner',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {16.4: {'batsman': 'TM Head',
    'bowler': 'SL Malinga',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {16.5: {'batsman': 'AJ Turner',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {16.6: {'batsman': 'TM Head',
    'bowler': 'SL Malinga',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {17.1: {'batsman': 'TM Head',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {17.2: {'batsman': 'AJ Turner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'TM Head',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {17.3: {'batsman': 'AJ Turner',
    'bowler': 'KMDN Kulasekara',
    'extras': {'noballs': 1},
    'non_striker': 'TM Head',
    'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
  {17.4: {'batsman': 'AJ Turner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {17.5: {'batsman': 'TM Head',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {17.6: {'batsman': 'AJ Turner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {17.7: {'batsman': 'TM Head',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {18.1: {'batsman': 'AJ Turner',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {18.2: {'batsman': 'AJ Turner',
    'bowler': 'SL Malinga',
    'non_striker': 'TM Head',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {18.3: {'batsman': 'TM Head',
    'bowler': 'SL Malinga',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {18.4: {'batsman': 'TM Head',
    'bowler': 'SL Malinga',
    'non_striker': 'AJ Turner',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0},
    'wicket': {'fielders': ['S Prasanna'],
     'kind': 'caught',
     'player_out': 'TM Head'}}},
  {18.5: {'batsman': 'AJ Turner',
    'bowler': 'SL Malinga',
    'non_striker': 'JP Faulkner',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0},
    'wicket': {'fielders': ['S Prasanna'],
     'kind': 'caught',
     'player_out': 'AJ Turner'}}},
  {18.6: {'batsman': 'JP Faulkner',
    'bowler': 'SL Malinga',
    'non_striker': 'TD Paine',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
  {19.1: {'batsman': 'JP Faulkner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'TD Paine',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
  {19.2: {'batsman': 'JP Faulkner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'TD Paine',
    'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
  {19.3: {'batsman': 'JP Faulkner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'TD Paine',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {19.4: {'batsman': 'JP Faulkner',
    'bowler': 'KMDN Kulasekara',
    'extras': {'wides': 1},
    'non_striker': 'TD Paine',
    'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
  {19.5: {'batsman': 'JP Faulkner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'TD Paine',
    'runs': {'batsman': 1, 'extras': 0, 'total': 1},
    'wicket': {'fielders': ['CK Kapugedera', 'KMDN Kulasekara'],
     'kind': 'run out',
     'player_out': 'TD Paine'}}},
  {19.6: {'batsman': 'JP Faulkner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'PJ Cummins',
    'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
  {19.7: {'batsman': 'JP Faulkner',
    'bowler': 'KMDN Kulasekara',
    'non_striker': 'PJ Cummins',
    'runs': {'batsman': 4, 'extras': 0, 'total': 4}}}]}

In [ ]:
count = 1
delivery_df = pd.DataFrame()
for index, row in final_df.iterrows():
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    delivery_df = pd.concat([delivery_df, loop_df])

In [123]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...,...,...
121,3359,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium
122,3359,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium
123,3359,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium
124,3359,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium
125,3359,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium

In [126]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [127]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [128]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...,...
121,3359,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
122,3359,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
123,3359,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
124,3359,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
125,3359,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [129]:
delivery_df.drop(columns=['teams'],inplace=True)

In [130]:
delivery_df['batting_team'].unique()

<StringArray>
[              'Australia',               'Hong Kong',
                'Zimbabwe',                   'India',
              'Bangladesh',             'New Zealand',
            'South Africa',                 'England',
             'West Indies',                'Pakistan',
 ...
                  'Mexico',                'Cambodia',
              'Costa Rica',                'Mongolia',
                  'Brazil',             'Ivory Coast',
                'Suriname', 'Turks and Caicos Island',
             'Timor-Leste',                  'Zambia']
Length: 106, dtype: str

In [131]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'    
]

In [133]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [134]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
122,3359,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
123,3359,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
124,3359,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
125,3359,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [135]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [136]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
122,3359,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
123,3359,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
124,3359,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
125,3359,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [138]:
pickle.dump(output,open('dataset.pkl','wb'))