In [74]:
import pandas as pd
import pickle
import numpy as np

In [75]:
df = pickle.load(open("dataset.pkl",'rb'))

In [76]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
122,3359,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
123,3359,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
124,3359,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
125,3359,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [77]:
df.isna().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8549
venue                  0
dtype: int64

In [78]:
df['venue'].apply(lambda x: x.split()[0])

0      Melbourne
1      Melbourne
2      Melbourne
3      Melbourne
4      Melbourne
         ...
121            R
122            R
123            R
124            R
125            R
Name: venue, Length: 111916, dtype: str

In [79]:
df[df['city'].isna()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        3092
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sylhet International Cricket Stadium        128
Sharjah Cricket Stadium                     127
Carrara Oval                                 64
Name: count, dtype: int64

In [80]:
cities = np.where(df['city'].isna(),df['venue'].str.split().apply(lambda x:x[0]),df['city'])

In [81]:
df['city'] = cities

In [82]:
df.isna().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [83]:
df.drop(columns=['venue'],inplace=True)

In [84]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,19.3,1,0,Colombo
122,3359,Sri Lanka,Australia,19.4,0,0,Colombo
123,3359,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
124,3359,Sri Lanka,Australia,19.6,2,0,Colombo
125,3359,Sri Lanka,Australia,19.7,1,0,Colombo

In [85]:
eligible_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.to_list()

In [86]:
eligible_cities

['Dubai',
 'Colombo',
 'Johannesburg',
 'Auckland',
 'Lahore',
 'Mirpur',
 'Dhaka',
 'Sydney',
 'Cape Town',
 'Christchurch',
 'London',
 'Wellington',
 'Melbourne',
 'Durban',
 'Lauderhill',
 'Abu Dhabi',
 'Pallekele',
 'Centurion',
 'Mount Maunganui',
 'Barbados',
 'Kandy',
 'Southampton',
 'Kolkata',
 'Hamilton',
 'Manchester',
 'Ahmedabad',
 'Gros Islet',
 'Mumbai',
 'Nottingham',
 'St Lucia',
 'Karachi',
 'Bridgetown',
 'Cardiff',
 'Adelaide',
 'Kingston',
 'Rawalpindi',
 'Tarouba',
 'Birmingham',
 'Dambulla',
 'Brisbane',
 "St George's",
 'Perth',
 'Sharjah',
 'Chittagong',
 'Delhi',
 'Basseterre',
 'Nagpur',
 'Providence',
 'Harare',
 'Chandigarh',
 'Rajkot',
 'Chattogram',
 'Napier',
 'Hobart',
 'Canberra',
 'Pune',
 'Bristol',
 'Chester-le-Street',
 'Bangalore',
 'Sylhet',
 'Trinidad',
 'Visakhapatnam']

In [87]:
df = df[df['city'].isin(eligible_cities)]

In [88]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,19.3,1,0,Colombo
122,3359,Sri Lanka,Australia,19.4,0,0,Colombo
123,3359,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
124,3359,Sri Lanka,Australia,19.6,2,0,Colombo
125,3359,Sri Lanka,Australia,19.7,1,0,Colombo

In [89]:
df['score'] = df.groupby('match_id')['runs'].cumsum()

In [90]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,score
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3
...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,19.3,1,0,Colombo,125
122,3359,Sri Lanka,Australia,19.4,0,0,Colombo,125
123,3359,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125
124,3359,Sri Lanka,Australia,19.6,2,0,Colombo,127
125,3359,Sri Lanka,Australia,19.7,1,0,Colombo,128

In [91]:
df['Over'] = df['ball'].apply(lambda x: str(x).split(".")[0])
df['ball'] = df['ball'].apply(lambda x: str(x).split(".")[1])

In [92]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,score,Over
0,2,Australia,Sri Lanka,1,0,0,Melbourne,0,0
1,2,Australia,Sri Lanka,2,0,0,Melbourne,0,0
2,2,Australia,Sri Lanka,3,1,0,Melbourne,1,0
3,2,Australia,Sri Lanka,4,2,0,Melbourne,3,0
4,2,Australia,Sri Lanka,5,0,0,Melbourne,3,0
...,...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,3,1,0,Colombo,125,19
122,3359,Sri Lanka,Australia,4,0,0,Colombo,125,19
123,3359,Sri Lanka,Australia,5,0,DM de Silva,Colombo,125,19
124,3359,Sri Lanka,Australia,6,2,0,Colombo,127,19
125,3359,Sri Lanka,Australia,7,1,0,Colombo,128,19

In [93]:
df['total_ball_bowled'] = df['Over'].astype(int)*6 + df['ball'].astype(int)

In [94]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,score,Over,total_ball_bowled
0,2,Australia,Sri Lanka,1,0,0,Melbourne,0,0,1
1,2,Australia,Sri Lanka,2,0,0,Melbourne,0,0,2
2,2,Australia,Sri Lanka,3,1,0,Melbourne,1,0,3
3,2,Australia,Sri Lanka,4,2,0,Melbourne,3,0,4
4,2,Australia,Sri Lanka,5,0,0,Melbourne,3,0,5
...,...,...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,3,1,0,Colombo,125,19,117
122,3359,Sri Lanka,Australia,4,0,0,Colombo,125,19,118
123,3359,Sri Lanka,Australia,5,0,DM de Silva,Colombo,125,19,119
124,3359,Sri Lanka,Australia,6,2,0,Colombo,127,19,120
125,3359,Sri Lanka,Australia,7,1,0,Colombo,128,19,121

In [95]:
df['balls_left'] = 120 - df['total_ball_bowled']

df['balls_left'] =  df['balls_left'].apply(lambda x: abs(x) if x < 0 else x)

In [96]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,score,Over,total_ball_bowled,balls_left
0,2,Australia,Sri Lanka,1,0,0,Melbourne,0,0,1,119
1,2,Australia,Sri Lanka,2,0,0,Melbourne,0,0,2,118
2,2,Australia,Sri Lanka,3,1,0,Melbourne,1,0,3,117
3,2,Australia,Sri Lanka,4,2,0,Melbourne,3,0,4,116
4,2,Australia,Sri Lanka,5,0,0,Melbourne,3,0,5,115
...,...,...,...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,3,1,0,Colombo,125,19,117,3
122,3359,Sri Lanka,Australia,4,0,0,Colombo,125,19,118,2
123,3359,Sri Lanka,Australia,5,0,DM de Silva,Colombo,125,19,119,1
124,3359,Sri Lanka,Australia,6,2,0,Colombo,127,19,120,0
125,3359,Sri Lanka,Australia,7,1,0,Colombo,128,19,121,1

In [97]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)

In [98]:
df['player_dismissed'] = df['player_dismissed'].astype('int')

In [99]:
df['player_dismissed'].info()

<class 'pandas.Series'>
Index: 98672 entries, 0 to 125
Series name: player_dismissed
Non-Null Count  Dtype
--------------  -----
98672 non-null  int64
dtypes: int64(1)
memory usage: 1.5 MB

In [100]:
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()

In [101]:
df['wickets_left'] = 10 - df['player_dismissed']

In [102]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,score,Over,total_ball_bowled,balls_left,wickets_left
0,2,Australia,Sri Lanka,1,0,0,Melbourne,0,0,1,119,10
1,2,Australia,Sri Lanka,2,0,0,Melbourne,0,0,2,118,10
2,2,Australia,Sri Lanka,3,1,0,Melbourne,1,0,3,117,10
3,2,Australia,Sri Lanka,4,2,0,Melbourne,3,0,4,116,10
4,2,Australia,Sri Lanka,5,0,0,Melbourne,3,0,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,3,1,8,Colombo,125,19,117,3,2
122,3359,Sri Lanka,Australia,4,0,8,Colombo,125,19,118,2,2
123,3359,Sri Lanka,Australia,5,0,9,Colombo,125,19,119,1,1
124,3359,Sri Lanka,Australia,6,2,9,Colombo,127,19,120,0,1
125,3359,Sri Lanka,Australia,7,1,9,Colombo,128,19,121,1,1

In [103]:
df['crr'] = (df['score']*6)/df['total_ball_bowled']

In [104]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,score,Over,total_ball_bowled,balls_left,wickets_left,crr
0,2,Australia,Sri Lanka,1,0,0,Melbourne,0,0,1,119,10,0.000000
1,2,Australia,Sri Lanka,2,0,0,Melbourne,0,0,2,118,10,0.000000
2,2,Australia,Sri Lanka,3,1,0,Melbourne,1,0,3,117,10,2.000000
3,2,Australia,Sri Lanka,4,2,0,Melbourne,3,0,4,116,10,4.500000
4,2,Australia,Sri Lanka,5,0,0,Melbourne,3,0,5,115,10,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,3,1,8,Colombo,125,19,117,3,2,6.410256
122,3359,Sri Lanka,Australia,4,0,8,Colombo,125,19,118,2,2,6.355932
123,3359,Sri Lanka,Australia,5,0,9,Colombo,125,19,119,1,1,6.302521
124,3359,Sri Lanka,Australia,6,2,9,Colombo,127,19,120,0,1,6.350000
125,3359,Sri Lanka,Australia,7,1,9,Colombo,128,19,121,1,1,6.347107

In [105]:
df.groupby('match_id')['runs'].rolling(window = 30).sum().values

array([nan, nan, nan, ..., 32., 33., 32.], shape=(98672,))

In [106]:
df['last_five'] = df.groupby('match_id')['runs'].rolling(window = 30).sum().values

In [107]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,score,Over,total_ball_bowled,balls_left,wickets_left,crr,last_five
0,2,Australia,Sri Lanka,1,0,0,Melbourne,0,0,1,119,10,0.000000,NaN
1,2,Australia,Sri Lanka,2,0,0,Melbourne,0,0,2,118,10,0.000000,NaN
2,2,Australia,Sri Lanka,3,1,0,Melbourne,1,0,3,117,10,2.000000,NaN
3,2,Australia,Sri Lanka,4,2,0,Melbourne,3,0,4,116,10,4.500000,NaN
4,2,Australia,Sri Lanka,5,0,0,Melbourne,3,0,5,115,10,3.600000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,3359,Sri Lanka,Australia,3,1,8,Colombo,125,19,117,3,2,6.410256,32.0
122,3359,Sri Lanka,Australia,4,0,8,Colombo,125,19,118,2,2,6.355932,32.0
123,3359,Sri Lanka,Australia,5,0,9,Colombo,125,19,119,1,1,6.302521,32.0
124,3359,Sri Lanka,Australia,6,2,9,Colombo,127,19,120,0,1,6.350000,33.0
125,3359,Sri Lanka,Australia,7,1,9,Colombo,128,19,121,1,1,6.347107,32.0

In [108]:
final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')

In [109]:
final_df=final_df[['batting_team','bowling_team','city','score','balls_left','wickets_left','crr','last_five','runs_x']]

In [110]:
final_df.isna().sum()

batting_team        0
bowling_team        0
city                0
score               0
balls_left          0
wickets_left        0
crr                 0
last_five       23574
runs_x              0
dtype: int64

In [111]:
final_df.dropna(inplace = True)

In [112]:
final_df

,batting_team,bowling_team,city,score,balls_left,wickets_left,crr,last_five,runs_x
29,Australia,Sri Lanka,Melbourne,43,90,10,8.600000,43.0,168
30,Australia,Sri Lanka,Melbourne,44,89,10,8.516129,44.0,168
31,Australia,Sri Lanka,Melbourne,45,88,10,8.437500,45.0,168
32,Australia,Sri Lanka,Melbourne,45,87,10,8.181818,44.0,168
33,Australia,Sri Lanka,Melbourne,45,86,10,7.941176,42.0,168
...,...,...,...,...,...,...,...,...,...
98667,Sri Lanka,Australia,Colombo,125,3,2,6.410256,32.0,128
98668,Sri Lanka,Australia,Colombo,125,2,2,6.355932,32.0,128
98669,Sri Lanka,Australia,Colombo,125,1,1,6.302521,32.0,128
98670,Sri Lanka,Australia,Colombo,127,0,1,6.350000,33.0,128
98671,Sri Lanka,Australia,Colombo,128,1,1,6.347107,32.0,128

In [113]:
# reshuffling to prevent develop any kind of bias
 
final_df = final_df.sample(final_df.shape[0])

In [114]:
final_df.sample(5)

,batting_team,bowling_team,city,score,balls_left,wickets_left,crr,last_five,runs_x
57518,Sri Lanka,England,Kandy,131,38,6,9.585366,39.0,189
54926,Bangladesh,Pakistan,Dhaka,72,42,6,5.538462,34.0,133
6718,India,Bangladesh,Colombo,68,64,10,7.285714,39.0,176
60564,Australia,New Zealand,Auckland,158,15,5,9.028571,44.0,214
68125,New Zealand,Pakistan,London,80,37,4,5.783133,26.0,99

In [115]:
X = final_df.drop('runs_x', axis =1 )
y = final_df['runs_x']

In [116]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from xgboost import XGBRegressor

In [117]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state= 42)

In [118]:
X_train

,batting_team,bowling_team,city,score,balls_left,wickets_left,crr,last_five
45390,Australia,Pakistan,Sydney,144,4,3,7.448276,39.0
2085,New Zealand,Australia,Sydney,76,34,5,5.302326,28.0
68954,Sri Lanka,Pakistan,London,54,59,6,5.311475,22.0
19326,South Africa,Pakistan,Lahore,48,73,4,6.127660,35.0
72537,India,Sri Lanka,St Lucia,90,59,9,8.852459,46.0
...,...,...,...,...,...,...,...,...
12929,South Africa,India,Chandigarh,68,64,9,7.285714,37.0
52589,Pakistan,Bangladesh,Lahore,185,10,6,10.090909,38.0
1552,West Indies,India,Lauderhill,71,68,8,8.192308,33.0
34260,New Zealand,West Indies,Kingston,123,16,5,7.096154,36.0
11830,Sri Lanka,Australia,Brisbane,39,81,8,6.000000,34.0

In [119]:
transformer = ColumnTransformer(
    [
        ("ohe", OneHotEncoder(sparse_output= False, drop= "first", handle_unknown= "ignore"), ['batting_team', 'bowling_team', 'city']),
        ("sc", StandardScaler(),['score', 'balls_left', 'wickets_left', 'crr', 'last_five'])
    ], remainder= 'passthrough'
)

In [126]:
model = XGBRegressor(n_estimators= 1000,learning_rate= 0.2, max_depth= 12,random_state= 42)

In [127]:
pipe = Pipeline(steps= [
    ('step1', transformer),
    ('step2', model )
])

In [128]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city']),
                                                 ('sc', StandardScaler(),
                                                  ['score', 'balls_left',
                                                   'wickets_left', 'crr',
                                                   'last_five'])])),
                ('step2',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              c...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.2,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=12, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=1000, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [129]:
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9853188991546631
1.9600855112075806

In [130]:
pickle.dump(pipe,open('model.pkl', 'wb'))

In [131]:
pickle.dump(df,open('df.pkl', 'wb'))